# Generated by Django 5.0 on 2023-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvupload",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
