# Generated by Django 5.0 on 2023-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_alter_csvupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvupload",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
